{{- if and .Values.telegram.botToken (not .Values.telegram.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "szerencsejatek-telegram-bot.fullname" . }}-telegram
  labels:
    {{- include "szerencsejatek-telegram-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.telegram.botToken | quote }}
{{- end }}
