apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: szerencsejatek-bot
  namespace: default
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: szerencsejatek-bot
